# services/svc-hrms-core/app/rekognition_service.py

import os
import boto3
from botocore.exceptions import ClientError
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# --- AWS Rekognition Configuration ---
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_REGION = os.getenv("AWS_REGION", "us-east-1") # Default to us-east-1 if not set
REKOGNITION_COLLECTION_ID = "ecstasy_os_employees_collection"

# --- Initialize Rekognition Client ---
try:
    rekognition_client = boto3.client(
        "rekognition",
        aws_access_key_id=AWS_ACCESS_KEY_ID,
        aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
        region_name=AWS_REGION
    )
    print("AWS Rekognition client initialized successfully.")
except Exception as e:
    print(f"Error initializing AWS Rekognition client: {e}")
    rekognition_client = None

# --- Service Functions ---

def initialize_collection():
    """
    Checks if the Rekognition collection exists and creates it if it doesn't.
    This should be run when the application starts up.
    """
    if not rekognition_client:
        print("Rekognition client is not initialized. Cannot create collection.")
        return

    try:
        response = rekognition_client.list_collections()
        if REKOGNITION_COLLECTION_ID not in response.get("CollectionIds", []):
            print(f"Collection '{REKOGNITION_COLLECTION_ID}' not found, creating it now.")
            rekognition_client.create_collection(CollectionId=REKOGNITION_COLLECTION_ID)
            print("Collection created successfully.")
        else:
            print(f"Collection '{REKOGNITION_COLLECTION_ID}' already exists.")
    except ClientError as e:
        print(f"An error occurred while initializing collection: {e}")

def index_face(image_bytes) -> str:
    """
    Adds a face from an image to our Rekognition collection.

    Args:
        image_bytes: The binary image data.

    Returns:
        The FaceId generated by Rekognition for the indexed face.

    Raises:
        Exception if no face is detected or if the API call fails.
    """
    if not rekognition_client:
        raise Exception("Rekognition client is not initialized.")

    try:
        response = rekognition_client.index_faces(
            CollectionId=REKOGNITION_COLLECTION_ID,
            Image={'Bytes': image_bytes},
            MaxFaces=1,
            QualityFilter="AUTO",
            DetectionAttributes=['DEFAULT']
        )

        if not response['FaceRecords']:
            raise Exception("No face detected in the provided image.")

        face_id = response['FaceRecords'][0]['Face']['FaceId']
        print(f"Successfully indexed face with FaceId: {face_id}")
        return face_id
    except ClientError as e:
        # Provide more specific error feedback
        if e.response['Error']['Code'] == 'InvalidParameterException':
            raise Exception("No face detected in the image. Please ensure the image is clear and contains a single face.")
        raise Exception(f"AWS Rekognition API error: {e}")


def search_for_face(image_bytes) -> str:
    """
    Searches for a matching face in the collection.

    Args:
        image_bytes: The binary image data of the face to verify.

    Returns:
        The FaceId of the best match if found with high confidence.

    Raises:
        Exception if no match is found or the API call fails.
    """
    if not rekognition_client:
        raise Exception("Rekognition client is not initialized.")

    try:
        response = rekognition_client.search_faces_by_image(
            CollectionId=REKOGNITION_COLLECTION_ID,
            Image={'Bytes': image_bytes},
            FaceMatchThreshold=90, # Stricter threshold for better accuracy
            MaxFaces=1
        )

        if response['FaceMatches']:
            match = response['FaceMatches'][0]
            confidence = match['Similarity']
            face_id = match['Face']['FaceId']
            print(f"Found matching face {face_id} with {confidence:.2f}% similarity.")
            return face_id
        else:
            raise Exception("No matching face found in the collection.")
    except ClientError as e:
        if e.response['Error']['Code'] == 'InvalidParameterException':
            raise Exception("Could not detect a face in the verification image. Please try again.")
        raise Exception(f"An AWS Rekognition error occurred during search: {e}")
