"""Add azure_person_id to user table

Revision ID: 4196e544a69f
Revises: 
Create Date: 2025-07-22 12:24:55.108868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4196e544a69f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('azure_person_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['azure_person_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'azure_person_id')
    # ### end Alembic commands ###
