"""Add target fields to audit_logs and defaults to timestamps

Revision ID: 8956d6114fed
Revises: 80c7af7fb124
Create Date: 2025-07-22 14:47:37.507408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8956d6114fed'
down_revision: Union[str, Sequence[str], None] = '80c7af7fb124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('target_type', sa.String(), nullable=True))
    op.add_column('audit_logs', sa.Column('target_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'target_id')
    op.drop_column('audit_logs', 'target_type')
    # ### end Alembic commands ###
