"""Replace azure_person_id with rekognition_face_id in user table

Revision ID: bf3218f8b5a7
Revises: d5a2b9b67fa3
Create Date: 2025-08-07 12:35:30.745288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf3218f8b5a7'
down_revision: Union[str, Sequence[str], None] = 'd5a2b9b67fa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rekognition_face_id', sa.String(), nullable=True))
    op.drop_constraint(op.f('users_azure_person_id_key'), 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['rekognition_face_id'])
    op.drop_column('users', 'azure_person_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('azure_person_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(op.f('users_azure_person_id_key'), 'users', ['azure_person_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'rekognition_face_id')
    # ### end Alembic commands ###
